### ISSUE TITLE
Add notification support for Hipchat

### ISSUE THREAD

**Issue by glower** [keel-hq/keel#124]
Hi,

in my company we just started to use keel (it's a super tool!) and we need support for hipchat. I will implement notifications and later approvals for hipchat. I will provide a PR for this, maybe it can be helpful for someone else.

**Comment by rusenask** [comment]
Hi,

Sounds awesome! Yeah, I guess notifications would be a nice first step as a new package here https://github.com/keel-hq/keel/tree/master/extension/notification. 

Regarding approvals (bot stuff) it might be more tricky. If we get notifications in I could try refactoring bot package to be more "app agnostic" since in theory it shouldn't matter where the message is coming from (slack, hipchat, rocketchat). This would save a lot of time in the future as more chat integrations are being added. 

If you have any questions or need help with anything, please let me know :)

**Comment by glower** [comment]
Hi, thx for the comment, the PR is out, hope it is all ok (my first PR for a open source project). Add a new notification provider was very easy. It could be cool to have similar system for the approvals bots. If you have time for refactoring its cool, otherwise I have time to do it as well, if it is ok for you.

**Comment by rusenask** [comment]
Hi, notifications PR looks good, however I don't use hipchat to test it out :) the problem with approvals and bot is that it uses two interfaces (slack real time messaging) and another slack webhooks based client.

I will move slack specific functions to a subpackage as the first step. Then, we will see how much is duplicated as I understand message structure might be different (bot name included or not).

**Comment by glower** [comment]
Cool, thx for the fast code review. I testet it with HipChat. I just did small refactoring by myself, If you wait for 5 min I will make a PR for it and you can have a look (just decline if you dont like it). I just moved all the bot code to some sub module. I don't think I can share any code from the slack.

**Comment by rusenask** [comment]
Sounds good, looking forward to see that PR :)

**Comment by glower** [comment]
I think it is a good idea. So now, as second approval bot is implemented I can see some patterns. We can try to define a meaningful interface for a bot. I would like to work on it. For now I think you can close this issue

**Comment by rusenask** [comment]
thanks @glower !
