### ISSUE TITLE
Do a POST upon changes detected

### ISSUE THREAD

**Issue by lomori** [keel-hq/keel#269]
Hi,

I know this is a bit different than the current functionality, but probably not that hard to implement with the code already in place.

I wonder if there could be a way to explicitly define an image to be watched and do a POST whenever changes are detected. The idea behind it is that we would like to trigger a CI build upon a base image change, like my docker image is based on alpine:latest and want to rebuild it through a CI pipeline whenever alpine:latest changes. Maybe creating a new resource like:

apiVersion: keel.sh/v1
kind: ImageWatcher
metadata:
  name: iw-test
  labels:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true" 
  annotations:
      keel.sh/pollSchedule: "@every 1m"
spec:
  image:
   - name: "alpine base watcher"
     image: alpine:latest
     command:
       type: post
       url: https://abc.com/build?token=weGHty

Regards,
Luiz

**Comment by rusenask** [comment]
Hi, I guess it could be a new provider that would report TrackedImages where you specify them yourself. And it would also get new trigger events for those images since they would be monitored. 

Provider would have to implement these methods:

```golang
// Provider - generic provider interface
type Provider interface {
	Submit(event types.Event) error
	TrackedImages() ([]*types.TrackedImage, error)
	GetName() string
	Stop()
}
```

Trigger calls `Submit(event types.Event) error` on providers when image is available. I guess then you could have your code there to just post a webhook somewhere :)

**Comment by rusenask** [comment]
closing due to age
