### ISSUE TITLE
matchPrerelease limits usage of pre-release tag semantic

### ISSUE THREAD

**Issue by kautsig** [keel-hq/keel#317]
Currently the function which checks if a new version is available handles the matchPreRelease configuration like this:

```
if matchPreRelease && currentVersion.Prerelease() != v.Prerelease() {
        continue
}
```
https://github.com/keel-hq/keel/blob/master/util/version/version.go#L107

This limits the usefulness, because it would be good to have multiple "unstable" pre-release versions, such as rc1 etc *and* limit their deployment to a different environment:

* `1.0.0-rc.1.dev`
* `1.0.0-rc.2.dev`
* `1.0.0-rc.3.dev`
* `1.0.0-rc.3.stage`

Semver would allow that, according to that definition:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version.

I'd suggest to add a configuration settings `matchPreReleaseFieldIndex` or similar, which allows to referring to a specific index in the pre-release field for that specific comparison. If that config is not set, then the full pre-release field should be used to maintain backwards compatibility.

While https://github.com/keel-hq/keel/issues/252 seems related, I think it's not exactly the same requirement.

**Comment by kautsig** [comment]
@rusenask If you think that's a reasonable requirement, I'd attempt an implementation and open a PR.

**Comment by rusenask** [comment]
Hi, I think policy `glob:1.0.0-rc*.dev` would work for this use case if you are using GCR pubsub/webhooks. 

It might also make sense to have some logic with pre-releases that just dictates how to handle those prerelease versions instead of trying to accommodate every possibility (for those we have `glob`, `regexp` and `force` now):) 

For example, by default `1.0.0-rc1.dev` -> `1.0.0-rc2.dev` it would get auto updates without any additional config. Maybe our semver library actually does this by default? Need to add a test for it, but it does try to be very helpful (https://github.com/Masterminds/semver)

**Comment by kautsig** [comment]
That sounds great, I'll try the suggestion. :+1: 

I was not aware of those policies yet, because of https://github.com/keel-hq/keel/issues/300

**Comment by rusenask** [comment]
Great :)
