### ISSUE TITLE
Feature Request: Slack Approval buttons

### ISSUE THREAD

**Issue by Martin-4Spaces** [keel-hq/keel#321]
It would be nice if keel implemented the slack message buttons for approval :)
https://api.slack.com/docs/message-buttons

**Comment by rusenask** [comment]
Hi, unfortunately this doesn't work through bot's RTM websocket. In order to get a buttons working it would require a public URL and more like backing SaaS that Keel would have to subscribe to for these events and I would have to host it + handle multi tenancy and so on.. :) I will look into it more, maybe we could just have a self hosted version with webhook relay that would keep everything inside Keel but it still might be a lot of effort. When I started doing approvals with Slack I initially wanted buttons as well..

**Comment by Martin-4Spaces** [comment]
Thank you for the explanation :)
