### ISSUE TITLE
Azure ACR webhook

### ISSUE THREAD

**Issue by Chams91** [keel-hq/keel#475]
can anyone provide a clear way on how to set up a webhook to my acr registry as i am seeking updating my newly updated images automatically with Keel?

the Keel documentation speciifes this endpoint: /v1/webhooks/azure but how to set it and wich uri?
i tried this..
$ az acr webhook create --registry mycontainerregistry --name myacrwebhook01 --actions push --uri http://webhookrelay.com/v1/webhooks/azure
 is it correct?

**Comment by rusenask** [comment]
hi, sorry for the enterprise level response delay :)) No, webhooks should be sent to where the keel is exposed (your-domain.example/com/v1/webhooks/azure)

Unless you are pairing it with Webhook Relay (like I do because it tends to be easier that configuring both.)

You can follow this example: https://keel.sh/examples/#set-up-github-repository

In this case you will be forwarding webhooks to something like https://my.webhookrelay.com/v1/webhooks/b968afa1-b737-4385-bc0f-473dbc2007b4

**Comment by Chams91** [comment]
hey @rusenask.. thanks for the support. should state the following.. the webhookrelay method isn´t the most ideal in our production scenario.. therefore we´re focusing on native webhooks with Azure CR. did proceed with that endpoint, but still no update is being done. One hesitation that i am having now, Should i mention keel service public ip or my app service public ip in the endpoint url?

**Comment by rusenask** [comment]
hmm not sure, maybe you can check what kind of payload is produced by Azure? then try POST'ing the same payload via curl or rest client (like https://insomnia.rest/)? Also, anything in the keel logs when it receives the webhook?
