### ISSUE TITLE
Github webhooks integration is broken

### ISSUE THREAD

**Issue by calvinli723** [keel-hq/keel#713]
When I use the "registry package" payload on github, I get:

"registry package type was not docker"

as response.

Also, when I use the "package" payload on github, nothing seems to happen. The code in pkg/http/github_webhook_trigger.go has a line looking for "package_v2" as event type for the payload, which I believe is just "package" now.

**Comment by joebowbeer** [comment]
Yes, the event type is just `package` now

https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#package

**Comment by bard** [comment]
Took a stab at this in https://github.com/keel-hq/keel/pull/741

If you want to test, use image ghcr.io/bard/keel:master

Note you also need to change webhook config in your repository so that "Packages" events are sent rather of "Registry Packages" (docs change at https://github.com/keel-hq/keel.sh/pull/50)

**Comment by bard** [comment]
Also, if anyone wants to test it, it's _temporarily_ available at ghcr.io/bard/keel:master

**Comment by joebowbeer** [comment]
@bard I think the failing unit test is still sending the "package_v2" header

https://github.com/bard/keel/blob/6c9f9a00935f6aaaf939fdc28fcf77d4ce0845ee/pkg/http/github_webhook_trigger_test.go#L383

Whereas you changed the expected header to "package"
